services:
  geth:
    image: ethereum/client-go:stable
    container_name: geth
    network_mode: host
    restart: unless-stopped
    ports:
      - 30303:30303
      - 30303:30303/udp
      - 8545:8545
      - 8546:8546
      - 8551:8551
    volumes:
      - /root/ethereum/execution:/data
      - /root/ethereum/jwt.hex:/data/jwt.hex
    command:
      - --sepolia
      - --http
      - --http.api=eth,net,web3
      - --http.addr=0.0.0.0
      - --authrpc.addr=0.0.0.0
      - --authrpc.vhosts=*
      - --authrpc.jwtsecret=/data/jwt.hex
      - --authrpc.port=8551
      - --syncmode=snap
      - --datadir=/data
      - --cache=17000
      - --maxpeers=40
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    cpus: 15.0
    mem_limit: "18g"
    mem_reservation: "18g"
    stop_grace_period: 10m
    ulimits:
      nofile:
        soft: 131072
        hard: 131072

  prysm:
    image: gcr.io/prysmaticlabs/prysm/beacon-chain
    container_name: prysm
    network_mode: host
    restart: unless-stopped
    volumes:
      - /root/ethereum/consensus:/data
      - /root/ethereum/jwt.hex:/data/jwt.hex
    depends_on:
      - geth
    ports:
      - 4000:4000
      - 3500:3500
    command:
      - --sepolia
      - --accept-terms-of-use
      - --datadir=/data
      - --disable-monitoring
      - --rpc-host=0.0.0.0
      - --execution-endpoint=http://127.0.0.1:8551
      - --jwt-secret=/data/jwt.hex
      - --rpc-port=4000
      - --grpc-gateway-corsdomain=*
      - --grpc-gateway-host=0.0.0.0
      - --grpc-gateway-port=3500
      - --checkpoint-sync-url=https://checkpoint-sync.sepolia.ethpandaops.io
      - --genesis-beacon-api-url=https://checkpoint-sync.sepolia.ethpandaops.io
      - --p2p-max-peers=55
      - --min-sync-peers=3
      - --minimum-peers-per-subnet=3
      - --max-goroutines=3000
      - --gc-percent=75
      - --p2p-tcp-port=13000
      - --p2p-udp-port=12000
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    cpus: 10.0
    mem_limit: "14g"
    mem_reservation: "13g"
    stop_grace_period: 10m
    ulimits:
      nofile:
        soft: 131072
        hard: 131072
